### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by Airon90** [vanilla-music/vanilla-music-tag-editor#1]
Add this plugin to F-Droid, so that it can be easily installed

**Comment by Adonai** [comment]
Should be built in next F-Droid update, see [this](https://gitlab.com/fdroid/fdroiddata/merge_requests/1944)

**Comment by Adonai** [comment]
Looks like they added Gradle 3.3 but forgot to re-initiate build processes... hmph

Okay, I'll push new tags after icon rework

**Comment by kirbyfan64** [comment]
What happened to this? :(

**Comment by Adonai** [comment]
F-Droid didn't support Cradle 3.3.

Will fix this issue on Sunday.

**Comment by Adonai** [comment]
F-Droid should schedule the build, will update once it does

**Comment by Adonai** [comment]
https://gitlab.com/fdroid/fdroidserver/issues/252

**Comment by kirbyfan64** [comment]
You should totally just make an APK of this and host it on a file-sharing site. For some reason, I feel like getting F-Droid to work is going to take a while...

**Comment by Adonai** [comment]
Just did it :) GitHub provides such option

[vanilla-tag-editor.apk](https://github.com/vanilla-music/vanilla-music-tag-editor/releases/download/1.0.2/vanilla-tag-editor.apk)

**Comment by Adonai** [comment]
It did pass through! Looks like my complaints finally made them install Gradle 3.3 on production build server.

Both plugins are present and with relevant icons: https://f-droid.org/repository/browse/?fdfilter=vanilla&fdpage=1&page_id=0
