### ISSUE TITLE
add opus support 

### ISSUE THREAD

**Issue by utack** [vanilla-music/vanilla-music-tag-editor#10]
Could you please add .opus support to the tag editor?  
It is not extremely popular, but a sane format for mobile devices with limited space (and in general)  
Would be much appreciated

**Comment by Adonai** [comment]
Not sure how, I use jaudiotagger lib that has no  support for Opus AFAIK: https://bitbucket.org/ijabz/jaudiotagger/issues/65/add-support-for-ogg-opus-format

**Comment by Adonai** [comment]
Closing this bug here,

Forwarded this request to upstream: https://bitbucket.org/ijabz/jaudiotagger/issues/65/add-support-for-ogg-opus-format
