### ISSUE TITLE
Tag Editor 1.1.1 crashes (same thing with 1.0.4 and 1.03)

### ISSUE THREAD

**Issue by tbbp** [vanilla-music/vanilla-music-tag-editor#11]
Hi everybody,
while trying to use the Vanilla Tag Editor 1.1.1 with Vanilla Music 1.0.50 on Android 6.0.1 the Tag Editor crashes when I try to fill in one of the tag fields.
Starting the Tag Editor I get the following very briefly shown Error message (I only could manage reading the message by making a screen shot of it):

> Error while working with audio file file:///storage/.../...m4a,
> This file does not appear to be an Mp4 Audio file, could be corruptet or video"

Same issue when I tried all available Vanilla Tag Editor versions from 1.0.3 to 1.0.4. or when I tried to use the Vanilla Cover Fetcher 1.0.1 or Vanilla Lyrics Search 1.0.3
By playing the Mp4A files in Vanilla Music 1.0.50 everything is working fine.
Thank you for your help!

**Comment by Adonai** [comment]
Not our bug actually, this is jadiotagger-android glitch.
You can report this bug [there](https://github.com/hexise/jaudiotagger-android), but it is unmaintained since Dec 2015.

Sadly, no one did port newer versions of jadiotagger to android.

**Comment by Adonai** [comment]
Closing this bug here.

Refer to upstream: https://bitbucket.org/ijabz/jaudiotagger/issues/198/cannotreadexception-with-m4a-file
