### ISSUE TITLE
Tag editor 1.2.0 crashes

### ISSUE THREAD

**Issue by bmassot** [vanilla-music/vanilla-music-tag-editor#12]
With Tag Editor 1.2.0, when I select "Plugins" on track contextual menu, then  "Tag editor" entry, Vanilla freezes for about 15 seconds. Then I get a "Unfortunately, Vanilla Tag Editor has stopped." message.

Switching back to Tag Editor 1.1.2 makes everything working fine.

Using Tag Editor 1.2.0 with Vanilla Music 1.0.52 from F-Droid, on Android 4.1.2.

**Comment by Adonai** [comment]
Fixing it now

**Comment by Adonai** [comment]
Should be fixed in 1.2.1. Wait for it to be released in F-Droid

**Comment by Adonai** [comment]
No answer from author, closing
