### ISSUE TITLE
Unable to save new metadata of files on SD card

### ISSUE THREAD

**Issue by airon90** [vanilla-music/vanilla-music-tag-editor#16]
The title self-explains the problem.
You cannot save new metadata of files on SD card because an exception is risen: 
![screenshot_2017-10-23-23-35-38](https://user-images.githubusercontent.com/139841/31914507-3c0873ec-b84b-11e7-94aa-23000cc1af65.png)

**Comment by Adonai** [comment]
How is this different from #3? Which version are you using?

**Comment by airon90** [comment]
Ok, didn't see that closed issue. Sorry. I'm using latest F-Droid version of Vanilla Music and tag editor on Android 5.1.1

**Comment by Adonai** [comment]
Will take a look this week, thanks

**Comment by Adonai** [comment]
@airon90, can't seem to reproduce the issue. Does Tag Editor ask for SD Card permission? Try clearing Tag Editor app data.

Here's how it goes for me:
![image](https://user-images.githubusercontent.com/863272/32157338-f055ff7e-bd53-11e7-9295-15239c960511.png)

![image](https://user-images.githubusercontent.com/863272/32157350-08af67c2-bd54-11e7-8e23-49041159a57a.png)

![image](https://user-images.githubusercontent.com/863272/32157361-13a02c34-bd54-11e7-8182-d78d2ff93744.png)

![image](https://user-images.githubusercontent.com/863272/32157369-23acf418-bd54-11e7-9b07-ae5544cfd29a.png)

![image](https://user-images.githubusercontent.com/863272/32157377-301c692c-bd54-11e7-94be-bc0ea618fe16.png)

![image](https://user-images.githubusercontent.com/863272/32157400-428ce3ca-bd54-11e7-84d7-66a85fcdb97e.png)

![image](https://user-images.githubusercontent.com/863272/32157410-4ef1deea-bd54-11e7-99b5-2875ce8c0665.png)

**Comment by airon90** [comment]
Thank you for your screenshots! By now it never happened that I had to allow SD access

**Comment by Adonai** [comment]
So, did clearing app data help?

**Comment by airon90** [comment]
(I didn't want to comment LOL :D)
I'm trying doing it but the options "Clear cache" and "Clear data" are unavailable yet. "Calculating"... I uninstall and reinstall it

**Comment by airon90** [comment]
Even uninstalling and reinstalling the app, permission is not asked

**Comment by Adonai** [comment]
OK, I'll try to replicate this exact version of Android.

**Comment by Adonai** [comment]
**5.1** doesn't trigger this behaviour, I can write to sdcard without any need to approve SAF storage.
Can't find any images of Android **5.1.1** in Google-provided virtual device set.

**Comment by airon90** [comment]
Write me if I should do something for you

**Comment by Adonai** [comment]
Does any file browser like Amaze work with these files? Can you write anything with it?

**Comment by airon90** [comment]
I can do that with Amaze and I succeded in renaming a file. I tried again with Vanilla but an error appeared again

**Comment by Adonai** [comment]
Took SAF detection from Amaze, pls try [this release](https://github.com/vanilla-music/vanilla-music-tag-editor/releases/download/1.2.5/app-debug.apk)

**Comment by airon90** [comment]
Yeah! It works! :)

**Comment by Adonai** [comment]
Good :+1: now let's hope it works for everyone else after F-Droid will update!
