### ISSUE TITLE
Scroll tags by letter

### ISSUE THREAD

**Issue by airon90** [vanilla-music/vanilla-music-tag-editor#17]
Custom tags are ordered alphabetically but you can't move between them by letter, like between tracks on Vanilla Music. I'd like to go rapidly to Y in order to select YEAR, I don't want to scroll all the tags until I reach YEAR ;)

**Comment by Adonai** [comment]
Sadly it's not possible, I use standard Android Spinner for tags dropdown and it doesn't have a support for fast scroll. I could possibly turn it into listview or recycleview but it will occupy a lot more space and we're already constrained by dialog borders :(

But if you have an idea or have seen an app with similar dropdowns, please let me know, I'll take a look.

**Comment by airon90** [comment]
Thank you for your answer :)
