### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by stemy2** [vanilla-music/vanilla-music-tag-editor#19]
Hello,

I can't use the plugin, the editor brutally closes when i'm typing a letter.

**Comment by Adonai** [comment]
Which version do you use? What file is this? What tag were you editing?

**Comment by stemy2** [comment]
Version: 1.2.6
File: a m4a file
It happens with any tag.

**Comment by Adonai** [comment]
Can you upload this file somewhere so I can reproduce this?

**Comment by Adonai** [comment]
Closed due to lack of details. Post here to reopen

**Comment by adrian-bl** [comment]
Fyi: i can reproduce this by trying to edit tags on opus files (which is probably just not supported - but the dialog will open and crash on first keyboard input)

**Comment by Adonai** [comment]
Hmmm, I'll try to take a look tomorrow

**Comment by justanidea** [comment]
So its just not possible to add tag to a .m4a file?

**Comment by justanidea** [comment]
Okey,  sad
Great job guys anyways 👌

**Comment by Adonai** [comment]
Done. With version 1.4.0 you can edit youtube m4a files.

**Comment by boggle247** [comment]
Using 1.4.2 (and tried 1.4.1 with same result) on Android 7.1.2 on a galaxy S5 (running LineageOS 14.1). Opengapps pico installed, although this should be irrelevant since I installed it via Fdroid.

Vanilla music player installed via Fdroid ver. 1.0.82

When I attempt to edit a mp4a file: long press file in tracks menu->plugins->tag editor then it flashes what looks like the editor, then the whole Vanilla music app crashes saying "Vanilla Tag Editor has Stopped". 

File is stored on an external SD card. App and plugin has permission to read & write to external SD card.

**Comment by Adonai** [comment]
Send this file to kanedias@keemail.me

**Comment by boggle247** [comment]
> Send this file to [kanedias@keemail.me](mailto:kanedias@keemail.me)

What file?

**Comment by Adonai** [comment]
The file you're trying to edit.

**Comment by Adonai** [comment]
The file you're trying to edit.

**Comment by boggle247** [comment]
Sent. I also just confirmed that it DOES allow me to edit mp3 files on my device. So it's definitely related to mp4a files. Any mp4a file I try to edit, it crashes like that. Thanks for the attentiveness!

**Comment by Adonai** [comment]
@boggle247 then I need your device info, as verbose as you can.

**Comment by Adonai** [comment]
OK, will try to reproduce it using matching emulator. Thanks.

**Comment by boggle247** [comment]
This https://androidfilehost.com/?fid=1395089523397902786 is the unofficial LOS14.1 rom I'm running. It's maintained by a LineageOS dev. and then like I said, running opengapps pico build for ARM (32bit) android 7.1.2. Thanks!

**Comment by Adonai** [comment]
Fixed in 54cf7cd, will be released as 1.4.3

Reason: JDK 1.7 doesn't have static `Integer.toUnsignedLong`, replaced with custom method.

**Comment by boggle247** [comment]
Awesome! Thank you so much!

**Comment by boggle247** [comment]
@Adonai fdroid just updated it and I confirmed that it's now working for myself. Thanks again.
