### ISSUE TITLE
Use distinct icon

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla-music-tag-editor#2]
It would be nice if the tag editor (+ lyrics plugin) used a unique icon.

This makes it simpler to spot the application in f-droid, the play store and in the system settings.

I'm not an artist, but something like the current icon + a pen might look nice

**Comment by Adonai** [comment]
Sounds good, but I'm no artist too. I'll have a look around and check if there's something appropriate.

**Comment by aminb** [comment]
No artist either, but current + "tag" or "label" might be cool too.

- [EasyTAG](https://wiki.gnome.org/Apps/EasyTAG)'s logo ([svg](https://git.gnome.org/browse/easytag/plain/data/icons/scalable/org.gnome.EasyTAG.svg), [symbolic](https://git.gnome.org/browse/easytag/plain/data/icons/symbolic/org.gnome.EasyTAG-symbolic.svg), [license](https://git.gnome.org/browse/easytag/plain/data/icons/license.md))):

![EasyTAG logo](https://git.gnome.org/browse/easytag/plain/data/icons/256x256/org.gnome.EasyTAG.png)

- Related Material icons:

  - https://material.io/icons/#ic_local_offer
  - https://material.io/icons/#ic_loyalty
  - https://material.io/icons/#ic_label
  - https://material.io/icons/#ic_label_outline
  - https://material.io/icons/#ic_edit

**Comment by Adonai** [comment]
How about this one?

**Comment by Adonai** [comment]
Ok, it made its' way to the F-Droid, I consider it done now.
Feel free to reopen in case it's inappropriate.
