### ISSUE TITLE
Cannot write LYRICS tag on external sd-card

### ISSUE THREAD

**Issue by francwalter** [vanilla-music/vanilla-music-tag-editor#20]
Hello
I try to set lyrics tags to my mp3 files on my external sd.
I have a Cubot Note Plus with Android 7.0 and the tag write plugin version 1.2.6
I allowed to write on external media after installing (Android permission).
But when I push the write button I get the error:
**Nothing selected from SAF file picker, exiting**
I read the closed issue #16 but that didn't help.
First I thought it's the lyrics plugin but [there I read](https://github.com/vanilla-music/vanilla-music-lyrics-search/issues/4) its here to find, because that plugin just uses tag editor plugin.
It can write a .lrc file though, but that doesn't help me, my player (PowerAmp) cannot use it.
How can I get things working?

Thanks, Frank

**Comment by francwalter** [comment]
I am sorry.
I just wanted to do a step-by-step list, what brings that error, but now it works!
It shows "File written successfully", after I press the Write button and Write to file tag.
And it was the first time, I got this dialog, where I can grant access to write to the sd-card.
I got this dialog before in this Tag Editor plugin, but never in the Lyrics search plugin.
So maybe I was wrong and this my previous error was anyway not Tag Editor Plugin related, but Lyrics Search Plugin only.
Sorry and thanks.

frank

**Comment by Adonai** [comment]
Sure. In case you somehow hit this again, pls describe it here so I could fix that.

Thanks.

**Comment by francwalter** [comment]
After i switched device i had the same issue again, with Tag Editor:
```Nothing selected from SAF file picker. Exiting```
I think the problem is, when the dialog with grant access to write to the sd-card ("SD card access required, steps below") is not popping up.
I reset data (in titanium backup) and the dialog came and the file write was successful :)
Maybe i restored the add-on with titanium with data, what was the cause then.

**Comment by Adonai** [comment]
@francwalter I already updated common library so it detects such condition.
It will take some time to accumulate changes to make new release for all the plugins using it, but eventually it will work alright.

Thanks for testing!

**Comment by francwalter** [comment]
And again I had it with the Tag Editor.
So I reset Data in Titanium for the Vanilla Tag Editor only and back it came the dialog to choose the permission for sd card and write :)

**Comment by francwalter** [comment]
And again.
I changed the sdcard, so Tag Editor and Lyrics search lost the write access to external sd-card.
This time i lost root (due to dec 19 update) and i reset data of Tag Writer plugin at system settings > Apps (data and cache).
After that i got the dialog again, could choose the new sdcard and it worked again.
I wonder if there is no other way to trigger that dialog.

**Comment by Adonai** [comment]
Please create new issue with "Support SD card change" title, I'll have a look
