### ISSUE TITLE
Blank tags

### ISSUE THREAD

**Issue by SebiderSushi** [vanilla-music/vanilla-music-tag-editor#25]
Please add the feature to delete tags! Right now, fields left blank don't cause the editor to delete these tags but set them to an empty value, which causes Vanilla to sort them to e.g. one new Album named ``.

**Comment by Adonai** [comment]
Fixed in 1.4.0, wait for it to be released or grab here.

[app-release.apk.zip](https://github.com/vanilla-music/vanilla-music-tag-editor/files/2858153/app-release.apk.zip)
