### ISSUE TITLE
Show more tags

### ISSUE THREAD

**Issue by SebiderSushi** [vanilla-music/vanilla-music-tag-editor#26]
Is it possible to automatically fill the edit window with more of the common tags like lyrics, composer, track-, and disknumber?
Also: Could it be possible to automatically offer to edit all tags that have values already written to them?

**Comment by andiandi13** [comment]
@Adonai : I was going to open the same issue and I totally agree.
Instead of letting us choose a specific tag at the bottom you should display a big windows with every written tag _and_ keep that choose-box at the bottom for empty tags.

**Comment by Adonai** [comment]
Hmm, makes sense. Let's do it.

**Comment by Adonai** [comment]
Fixed in 1.4.0, wait for it to be released or grab here.

[app-release.apk.zip](https://github.com/vanilla-music/vanilla-music-tag-editor/files/2858153/app-release.apk.zip)
