### ISSUE TITLE
Tag editor closes upon opening

### ISSUE THREAD

**Issue by citizen2947294** [vanilla-music/vanilla-music-tag-editor#28]
This was found when trying to write tags to an opus file with the fetcher. The fetcher works so we're moving the issue here.

Original fetcher issue:

When writing to opus, "Error while working with audio file / /path/filename.opus, No Reader associated with this extension:opus"

**Comment by Adonai** [comment]
Possibly related to #10 

JAudioTagger never added opus support and it seems that development is stalled now. I'll leave this issue open, maybe the time will come when I dive into its source.

**Comment by Adonai** [comment]
Actual implementation: https://github.com/Adonai/jaudiotagger/commit/e2e9e37ce5ee387c96ec90af6c4c8760aa775ef9
