### ISSUE TITLE
[Feature] Implement COVER_ART image selector

### ISSUE THREAD

**Issue by SebiderSushi** [vanilla-music/vanilla-music-tag-editor#33]
maybe copypaste the feature from the cover fetcher plugin

otherwise, less important since said plugin can still be used

**Comment by Adonai** [comment]
That's exactly what cover fetcher plugin is for :)
I may pick this up when I will remake tag editor into standalone app, in that case I'll reopen it

**Comment by SebiderSushi** [comment]
fair enough :)
