### ISSUE TITLE
Can't edit Artist and other tags

### ISSUE THREAD

**Issue by jhoc2000** [vanilla-music/vanilla-music-tag-editor#35]
I'm using tag editor Version 1.4.10. If I try to edit the 'Artist' or other tags that are not already in the present window there's nowhere to enter the text. All that is presented is the actual tag name (for example 'Artist') but I can't enter any thing. (Please see screenshot)
Can this be fixed please? 

![Screenshot_Tag_Editor](https://user-images.githubusercontent.com/16982707/89135265-c156d180-d56f-11ea-8f8e-6f7d11b4a8ac.png)

**Comment by Adonai** [comment]
Hmmm you're right, I can reproduce this. Will take a look on weekend.

**Comment by jhoc2000** [comment]
Did you find a solution for this?

**Comment by Adonai** [comment]
Actually, I found out that the first misleading titles like "Song artist" etc. actually track TITLE, ARTIST and ALBUM tag keys.

**Comment by Adonai** [comment]
Will probably rename them in future release
