### ISSUE TITLE
Vanilla Nightly

### ISSUE THREAD

**Issue by Airon90** [vanilla-music/vanilla-music-tag-editor#4]
I have the same problem with [Vanilla Music Lyrics](https://github.com/vanilla-music/vanilla-music-lyrics-search/issues/1). It doesn't work on Vanilla Nightly as no Plugins option can be found when long pressing a track

**Comment by Adonai** [comment]
@adrian-bl , can you share the script you use to remap package name from vanilla to vanilla-nightly?

**Comment by Adonai** [comment]
@adrian-bl , this still stands

**Comment by adrian-bl** [comment]
Didn't i post this recently to some other report?

Anyway: here it is again: https://gist.github.com/adrian-bl/f844e936c3154d729557e9d4ba8d0b87
