### ISSUE TITLE
Releasing APKs with each commit

### ISSUE THREAD

**Issue by dudedaoud** [vanilla-music/vanilla-music-tag-editor#5]
Plugins dont work for me. When i press plugins nothings append. And i think i need root to write tag on sd card ? Or need tout have access to sdcard.... Good job dev' thx. Android 5.0 Alcatel Idol 3s

**Comment by Adonai** [comment]
No, you don't need root to write to sdcard.

What versions of vanilla and plugins are you using?

**Comment by dudedaoud** [comment]
Hi,

I have 1.0.49 for Vanilla music and 1.0.3 to vanilla tag editor. 1.0.1 for
Vanilla cover fetcher.

I have plugins to the menu but nothing when i clic on.



2017-02-10 8:56 GMT+01:00 Antic1tizen One <notifications@github.com>:

**Comment by Adonai** [comment]
Are you using Vanilla Nightly?

**Comment by Adonai** [comment]
@dudedaoud , hey, are you reading?

**Comment by dudedaoud** [comment]
Yes. Sorry. I dont test the nicht
ly built. I test. Thx

Le 18 févr. 2017 18:47, "Antic1tizen One" <notifications@github.com> a
écrit :

**Comment by rancidfrog** [comment]
Tested latest nightly and plugins appear but clicking it does nothing.

**Comment by Adonai** [comment]
Because this kind of change was rejected by Adrian Ulrich, the maintainer of Vanilla Music

**Comment by rancidfrog** [comment]
Ah okay.
Either way, when clicking plugins nothing happened.

**Comment by rancidfrog** [comment]
https://github.com/vanilla-music/vanilla-music-tag-editor/commit/24ba4c5727dd3148e3aecd5731df2b6f21f6798e
Is the issue resolved?

https://github.com/vanilla-music/vanilla-music-tag-editor/releases/tag/1.0.2
Updated release with apk possible?
 https://github.com/vanilla-music/vanilla-music-tag-editor/releases/tag/1.1.2

**Comment by Adonai** [comment]
Can you fetch one from F-Droid? I believe they rebuild their apks after tag is pushed

**Comment by rancidfrog** [comment]
Latest version 1.1.2 which has commit is not on f-droid, only 1.1.1 is.

**Comment by rancidfrog** [comment]
Both
- https://play.google.com/store/apps/details?id=com.kanedias.vanilla.audiotag
- https://f-droid.org/repository/browse/?fdfilter=vanilla&fdid=com.kanedias.vanilla.audiotag
Do not have 1.1.2
Is it possible to include apk with each release?
https://github.com/vanilla-music/vanilla-music-tag-editor/releases
Like https://github.com/vanilla-music/vanilla-music-tag-editor/releases/tag/1.0.2

**Comment by Adonai** [comment]
> Is it possible to include apk with each release?

Certainly, I just have to make Travis integration work.

**Comment by Adonai** [comment]
Done, each tag pushed into repo triggers a Travis job that compiles the APK and attaches it to [Releases](https://github.com/vanilla-music/vanilla-music-tag-editor/releases) page
