### ISSUE TITLE
I'm seeing angle brackets

### ISSUE THREAD

**Issue by Rbagman** [vanilla-music/vanilla-music-tag-editor#6]
Android 4.4.2
In the tracks tab I see angle brackets. In the notification I see the file name(?) in angle brackets followed by
<No Artist>
<No Album>

**Comment by Adonai** [comment]
I'm sorry, what? Can you elaborate a bit?

**Comment by Adonai** [comment]
Closed as nonconstructive

**Comment by aminb** [comment]
@Adonai He'd posted html tags that GitHub didn't display.

This is his comment:

---

Android 4.4.2
In the tracks tab I see angle brackets. In the notification I see the file name(?) in angle brackets followed by
```
<No Artist>
<No Album>
  ```

**Comment by Adonai** [comment]
Well... ok! But that's Vanilla Player issue, not tag editor's
