### ISSUE TITLE
Tag editor 1.0.3 crashes

### ISSUE THREAD

**Issue by bmassot** [vanilla-music/vanilla-music-tag-editor#7]
With Tag Editor 1.0.3, when I select "Plugins" on track contextual menu, Vanilla freezes for about 15 seconds, before even getting the "Tag editor" button. Then I get a "Unfortunately, Vanilla Tag Editor has stopped." message.

Switching back to Tag Editor 1.0.2 makes everything working fine.

Using Tag Editor 1.0.3 with Vanilla  Music 1.0.48 from F-Droid, on Android 4.1.2.

**Comment by Adonai** [comment]
Strange, you're right!

Android 4.1.2 somehow understands "no `exported` attribute" as "it is exported!", while all subsequent versions understand it as "it is not exported!"

I'll add explicit `exported="false"`, wait for version 1.0.4 on F-Droid

**Comment by bmassot** [comment]
Thank you! By the way, same thing happens with Cover Fetcher.

**Comment by Adonai** [comment]
Hi, was the issue fixed?

**Comment by bmassot** [comment]
Actually I'm still waiting for 1.0.4 to be released on F-Droid.

**Comment by Adonai** [comment]
@bmassot , got it, I'll check their builds to see if something happened

**Comment by bmassot** [comment]
1.0.4 is now in F-Droid and works fine. Same thing for Cover Fetcher.

**Comment by magowiz** [comment]
Same issue on Android lollipop 5.1 with vanilla music 1.0.49 and tried all available vanilla tag editor versions from 1.0.2 to 1.0.4. When starting typing in the song title field it crashes.

**Comment by Adonai** [comment]
I guess this was resolved a while ago
